name: deploy01.yml

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0' ]

    steps:
      - name: Setup .NET 7.0
        uses: actions/checkout@v4
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
