name: deploy03.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # 또는 windows-latest, macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.401' # 원하는 6.0.x 버전으로 변경 가능
    #- name: Install dependencies
    #  run: dotnet add package Newtonsoft.Json --version 12.0.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: 
        dotnet build --no-restore
    - name: Publish # 배포 단계 추가
      run: dotnet publish --no-build -c Release -o ./publish
